// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_mock.proto

package com.emc.mongoose.storage.mock.impl.proto;

public final class StorageMockProto {
  private StorageMockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.emc.mongoose.storage.mock.proto.ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string containerName = 1 [default = ""];</code>
     */
    boolean hasContainerName();
    /**
     * <code>required string containerName = 1 [default = ""];</code>
     */
    java.lang.String getContainerName();
    /**
     * <code>required string containerName = 1 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getContainerNameBytes();

    /**
     * <code>required string id = 2 [default = ""];</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 2 [default = ""];</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required fixed64 offset = 3 [default = 0];</code>
     */
    boolean hasOffset();
    /**
     * <code>required fixed64 offset = 3 [default = 0];</code>
     */
    long getOffset();

    /**
     * <code>required fixed64 size = 4 [default = 0];</code>
     */
    boolean hasSize();
    /**
     * <code>required fixed64 size = 4 [default = 0];</code>
     */
    long getSize();
  }
  /**
   * Protobuf type {@code com.emc.mongoose.storage.mock.proto.ClientMessage}
   */
  public  static final class ClientMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.emc.mongoose.storage.mock.proto.ClientMessage)
      ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientMessage() {
      containerName_ = "";
      id_ = "";
      offset_ = 0L;
      size_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              containerName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              id_ = bs;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              offset_ = input.readFixed64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              size_ = input.readFixed64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.class, com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CONTAINERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object containerName_;
    /**
     * <code>required string containerName = 1 [default = ""];</code>
     */
    public boolean hasContainerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string containerName = 1 [default = ""];</code>
     */
    public java.lang.String getContainerName() {
      java.lang.Object ref = containerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          containerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string containerName = 1 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getContainerNameBytes() {
      java.lang.Object ref = containerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 2 [default = ""];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string id = 2 [default = ""];</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 3;
    private long offset_;
    /**
     * <code>required fixed64 offset = 3 [default = 0];</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required fixed64 offset = 3 [default = 0];</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int SIZE_FIELD_NUMBER = 4;
    private long size_;
    /**
     * <code>required fixed64 size = 4 [default = 0];</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required fixed64 size = 4 [default = 0];</code>
     */
    public long getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContainerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, containerName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, offset_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed64(4, size_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, containerName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, offset_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(4, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage)) {
        return super.equals(obj);
      }
      com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage other = (com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage) obj;

      boolean result = true;
      result = result && (hasContainerName() == other.hasContainerName());
      if (hasContainerName()) {
        result = result && getContainerName()
            .equals(other.getContainerName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasOffset() == other.hasOffset());
      if (hasOffset()) {
        result = result && (getOffset()
            == other.getOffset());
      }
      result = result && (hasSize() == other.hasSize());
      if (hasSize()) {
        result = result && (getSize()
            == other.getSize());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasContainerName()) {
        hash = (37 * hash) + CONTAINERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getContainerName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOffset());
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSize());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.emc.mongoose.storage.mock.proto.ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.emc.mongoose.storage.mock.proto.ClientMessage)
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.class, com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.Builder.class);
      }

      // Construct using com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        containerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_descriptor;
      }

      public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage getDefaultInstanceForType() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.getDefaultInstance();
      }

      public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage build() {
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage buildPartial() {
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage result = new com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.containerName_ = containerName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage) {
          return mergeFrom((com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage other) {
        if (other == com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage.getDefaultInstance()) return this;
        if (other.hasContainerName()) {
          bitField0_ |= 0x00000001;
          containerName_ = other.containerName_;
          onChanged();
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContainerName()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasOffset()) {
          return false;
        }
        if (!hasSize()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object containerName_ = "";
      /**
       * <code>required string containerName = 1 [default = ""];</code>
       */
      public boolean hasContainerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string containerName = 1 [default = ""];</code>
       */
      public java.lang.String getContainerName() {
        java.lang.Object ref = containerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            containerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string containerName = 1 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getContainerNameBytes() {
        java.lang.Object ref = containerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          containerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string containerName = 1 [default = ""];</code>
       */
      public Builder setContainerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        containerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string containerName = 1 [default = ""];</code>
       */
      public Builder clearContainerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        containerName_ = getDefaultInstance().getContainerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string containerName = 1 [default = ""];</code>
       */
      public Builder setContainerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        containerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 2 [default = ""];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string id = 2 [default = ""];</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 2 [default = ""];</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2 [default = ""];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2 [default = ""];</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>required fixed64 offset = 3 [default = 0];</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required fixed64 offset = 3 [default = 0];</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>required fixed64 offset = 3 [default = 0];</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000004;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 offset = 3 [default = 0];</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000004);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>required fixed64 size = 4 [default = 0];</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required fixed64 size = 4 [default = 0];</code>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>required fixed64 size = 4 [default = 0];</code>
       */
      public Builder setSize(long value) {
        bitField0_ |= 0x00000008;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 size = 4 [default = 0];</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        size_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.emc.mongoose.storage.mock.proto.ClientMessage)
    }

    // @@protoc_insertion_point(class_scope:com.emc.mongoose.storage.mock.proto.ClientMessage)
    private static final com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage();
    }

    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ClientMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ClientMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.emc.mongoose.storage.mock.proto.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed64 maskRangesRead = 1;</code>
     */
    boolean hasMaskRangesRead();
    /**
     * <code>required fixed64 maskRangesRead = 1;</code>
     */
    long getMaskRangesRead();

    /**
     * <code>required int32 layerNum = 2 [default = 0];</code>
     */
    boolean hasLayerNum();
    /**
     * <code>required int32 layerNum = 2 [default = 0];</code>
     */
    int getLayerNum();

    /**
     * <code>required int64 position = 3 [default = 0];</code>
     */
    boolean hasPosition();
    /**
     * <code>required int64 position = 3 [default = 0];</code>
     */
    long getPosition();

    /**
     * <code>required string containerName = 4 [default = ""];</code>
     */
    boolean hasContainerName();
    /**
     * <code>required string containerName = 4 [default = ""];</code>
     */
    java.lang.String getContainerName();
    /**
     * <code>required string containerName = 4 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getContainerNameBytes();

    /**
     * <code>required string id = 5 [default = ""];</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 5 [default = ""];</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 5 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required int64 offset = 6 [default = 0];</code>
     */
    boolean hasOffset();
    /**
     * <code>required int64 offset = 6 [default = 0];</code>
     */
    long getOffset();

    /**
     * <code>required fixed64 size = 7 [default = 0];</code>
     */
    boolean hasSize();
    /**
     * <code>required fixed64 size = 7 [default = 0];</code>
     */
    long getSize();
  }
  /**
   * Protobuf type {@code com.emc.mongoose.storage.mock.proto.ServerMessage}
   */
  public  static final class ServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.emc.mongoose.storage.mock.proto.ServerMessage)
      ServerMessageOrBuilder {
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMessage() {
      maskRangesRead_ = 0L;
      layerNum_ = 0;
      position_ = 0L;
      containerName_ = "";
      id_ = "";
      offset_ = 0L;
      size_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              maskRangesRead_ = input.readFixed64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              layerNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              position_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              containerName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              id_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              offset_ = input.readInt64();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              size_ = input.readFixed64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.class, com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MASKRANGESREAD_FIELD_NUMBER = 1;
    private long maskRangesRead_;
    /**
     * <code>required fixed64 maskRangesRead = 1;</code>
     */
    public boolean hasMaskRangesRead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed64 maskRangesRead = 1;</code>
     */
    public long getMaskRangesRead() {
      return maskRangesRead_;
    }

    public static final int LAYERNUM_FIELD_NUMBER = 2;
    private int layerNum_;
    /**
     * <code>required int32 layerNum = 2 [default = 0];</code>
     */
    public boolean hasLayerNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 layerNum = 2 [default = 0];</code>
     */
    public int getLayerNum() {
      return layerNum_;
    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private long position_;
    /**
     * <code>required int64 position = 3 [default = 0];</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 position = 3 [default = 0];</code>
     */
    public long getPosition() {
      return position_;
    }

    public static final int CONTAINERNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object containerName_;
    /**
     * <code>required string containerName = 4 [default = ""];</code>
     */
    public boolean hasContainerName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string containerName = 4 [default = ""];</code>
     */
    public java.lang.String getContainerName() {
      java.lang.Object ref = containerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          containerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string containerName = 4 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getContainerNameBytes() {
      java.lang.Object ref = containerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 5 [default = ""];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string id = 5 [default = ""];</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 5 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 6;
    private long offset_;
    /**
     * <code>required int64 offset = 6 [default = 0];</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 offset = 6 [default = 0];</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int SIZE_FIELD_NUMBER = 7;
    private long size_;
    /**
     * <code>required fixed64 size = 7 [default = 0];</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required fixed64 size = 7 [default = 0];</code>
     */
    public long getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMaskRangesRead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLayerNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContainerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, maskRangesRead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, layerNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, position_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, containerName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, offset_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFixed64(7, size_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, maskRangesRead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, layerNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, position_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, containerName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, offset_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(7, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage)) {
        return super.equals(obj);
      }
      com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage other = (com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage) obj;

      boolean result = true;
      result = result && (hasMaskRangesRead() == other.hasMaskRangesRead());
      if (hasMaskRangesRead()) {
        result = result && (getMaskRangesRead()
            == other.getMaskRangesRead());
      }
      result = result && (hasLayerNum() == other.hasLayerNum());
      if (hasLayerNum()) {
        result = result && (getLayerNum()
            == other.getLayerNum());
      }
      result = result && (hasPosition() == other.hasPosition());
      if (hasPosition()) {
        result = result && (getPosition()
            == other.getPosition());
      }
      result = result && (hasContainerName() == other.hasContainerName());
      if (hasContainerName()) {
        result = result && getContainerName()
            .equals(other.getContainerName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasOffset() == other.hasOffset());
      if (hasOffset()) {
        result = result && (getOffset()
            == other.getOffset());
      }
      result = result && (hasSize() == other.hasSize());
      if (hasSize()) {
        result = result && (getSize()
            == other.getSize());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMaskRangesRead()) {
        hash = (37 * hash) + MASKRANGESREAD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMaskRangesRead());
      }
      if (hasLayerNum()) {
        hash = (37 * hash) + LAYERNUM_FIELD_NUMBER;
        hash = (53 * hash) + getLayerNum();
      }
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPosition());
      }
      if (hasContainerName()) {
        hash = (37 * hash) + CONTAINERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getContainerName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOffset());
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSize());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.emc.mongoose.storage.mock.proto.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.emc.mongoose.storage.mock.proto.ServerMessage)
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.class, com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.Builder.class);
      }

      // Construct using com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        maskRangesRead_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        layerNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        position_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        containerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_descriptor;
      }

      public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage getDefaultInstanceForType() {
        return com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.getDefaultInstance();
      }

      public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage build() {
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage buildPartial() {
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage result = new com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maskRangesRead_ = maskRangesRead_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.layerNum_ = layerNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.containerName_ = containerName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage) {
          return mergeFrom((com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage other) {
        if (other == com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage.getDefaultInstance()) return this;
        if (other.hasMaskRangesRead()) {
          setMaskRangesRead(other.getMaskRangesRead());
        }
        if (other.hasLayerNum()) {
          setLayerNum(other.getLayerNum());
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (other.hasContainerName()) {
          bitField0_ |= 0x00000008;
          containerName_ = other.containerName_;
          onChanged();
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000010;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMaskRangesRead()) {
          return false;
        }
        if (!hasLayerNum()) {
          return false;
        }
        if (!hasPosition()) {
          return false;
        }
        if (!hasContainerName()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasOffset()) {
          return false;
        }
        if (!hasSize()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long maskRangesRead_ ;
      /**
       * <code>required fixed64 maskRangesRead = 1;</code>
       */
      public boolean hasMaskRangesRead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed64 maskRangesRead = 1;</code>
       */
      public long getMaskRangesRead() {
        return maskRangesRead_;
      }
      /**
       * <code>required fixed64 maskRangesRead = 1;</code>
       */
      public Builder setMaskRangesRead(long value) {
        bitField0_ |= 0x00000001;
        maskRangesRead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 maskRangesRead = 1;</code>
       */
      public Builder clearMaskRangesRead() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maskRangesRead_ = 0L;
        onChanged();
        return this;
      }

      private int layerNum_ ;
      /**
       * <code>required int32 layerNum = 2 [default = 0];</code>
       */
      public boolean hasLayerNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 layerNum = 2 [default = 0];</code>
       */
      public int getLayerNum() {
        return layerNum_;
      }
      /**
       * <code>required int32 layerNum = 2 [default = 0];</code>
       */
      public Builder setLayerNum(int value) {
        bitField0_ |= 0x00000002;
        layerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 layerNum = 2 [default = 0];</code>
       */
      public Builder clearLayerNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        layerNum_ = 0;
        onChanged();
        return this;
      }

      private long position_ ;
      /**
       * <code>required int64 position = 3 [default = 0];</code>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 position = 3 [default = 0];</code>
       */
      public long getPosition() {
        return position_;
      }
      /**
       * <code>required int64 position = 3 [default = 0];</code>
       */
      public Builder setPosition(long value) {
        bitField0_ |= 0x00000004;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 position = 3 [default = 0];</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000004);
        position_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object containerName_ = "";
      /**
       * <code>required string containerName = 4 [default = ""];</code>
       */
      public boolean hasContainerName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string containerName = 4 [default = ""];</code>
       */
      public java.lang.String getContainerName() {
        java.lang.Object ref = containerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            containerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string containerName = 4 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getContainerNameBytes() {
        java.lang.Object ref = containerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          containerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string containerName = 4 [default = ""];</code>
       */
      public Builder setContainerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        containerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string containerName = 4 [default = ""];</code>
       */
      public Builder clearContainerName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        containerName_ = getDefaultInstance().getContainerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string containerName = 4 [default = ""];</code>
       */
      public Builder setContainerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        containerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 5 [default = ""];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string id = 5 [default = ""];</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 5 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 5 [default = ""];</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 5 [default = ""];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 5 [default = ""];</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>required int64 offset = 6 [default = 0];</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 offset = 6 [default = 0];</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>required int64 offset = 6 [default = 0];</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000020;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 offset = 6 [default = 0];</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000020);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>required fixed64 size = 7 [default = 0];</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required fixed64 size = 7 [default = 0];</code>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>required fixed64 size = 7 [default = 0];</code>
       */
      public Builder setSize(long value) {
        bitField0_ |= 0x00000040;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 size = 7 [default = 0];</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        size_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.emc.mongoose.storage.mock.proto.ServerMessage)
    }

    // @@protoc_insertion_point(class_scope:com.emc.mongoose.storage.mock.proto.ServerMessage)
    private static final com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage();
    }

    public static com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    public com.emc.mongoose.storage.mock.impl.proto.StorageMockProto.ServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022storage_mock.proto\022#com.emc.mongoose.s" +
      "torage.mock.proto\"Z\n\rClientMessage\022\027\n\rco" +
      "ntainerName\030\001 \002(\t:\000\022\014\n\002id\030\002 \002(\t:\000\022\021\n\006off" +
      "set\030\003 \002(\006:\0010\022\017\n\004size\030\004 \002(\006:\0010\"\234\001\n\rServer" +
      "Message\022\026\n\016maskRangesRead\030\001 \002(\006\022\023\n\010layer" +
      "Num\030\002 \002(\005:\0010\022\023\n\010position\030\003 \002(\003:\0010\022\027\n\rcon" +
      "tainerName\030\004 \002(\t:\000\022\014\n\002id\030\005 \002(\t:\000\022\021\n\006offs" +
      "et\030\006 \002(\003:\0010\022\017\n\004size\030\007 \002(\006:\00102\223\001\n\026BasicSt" +
      "orageMockServer\022y\n\rManageRequest\0222.com.e" +
      "mc.mongoose.storage.mock.proto.ClientMes",
      "sage\0322.com.emc.mongoose.storage.mock.pro" +
      "to.ServerMessage\"\000B<\n(com.emc.mongoose.s" +
      "torage.mock.impl.protoB\020StorageMockProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_emc_mongoose_storage_mock_proto_ClientMessage_descriptor,
        new java.lang.String[] { "ContainerName", "Id", "Offset", "Size", });
    internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_emc_mongoose_storage_mock_proto_ServerMessage_descriptor,
        new java.lang.String[] { "MaskRangesRead", "LayerNum", "Position", "ContainerName", "Id", "Offset", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
