package com.emc.mongoose.load.step.slave;

import com.emc.mongoose.env.Extension;
import com.emc.mongoose.metrics.MetricsSnapshot;
import com.emc.mongoose.svc.ServiceBase;
import com.emc.mongoose.load.step.LoadStep;
import com.emc.mongoose.load.step.LoadStepService;
import com.emc.mongoose.load.step.LoadStepFactory;
import com.emc.mongoose.logging.Loggers;
import static com.emc.mongoose.Constants.KEY_CLASS_NAME;
import static com.emc.mongoose.Constants.KEY_STEP_ID;

import com.github.akurilov.confuse.Config;

import org.apache.logging.log4j.CloseableThreadContext;
import static org.apache.logging.log4j.CloseableThreadContext.Instance;

import java.io.IOException;
import java.rmi.RemoteException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

public final class BasicLoadStepService
extends ServiceBase
implements LoadStepService {

	private final LoadStep loadStep;

	public BasicLoadStepService(
		final int port, final List<Extension> extensions, final String stepType, final Config config,
		final List<Map<String, Object>> stepConfigs
	) {
		super(port);

		// don't override the step-id value on the remote node again
		config.val("load-step-idAutoGenerated", false);

		final List<LoadStepFactory> loadStepFactories = extensions
			.stream()
			.filter(ext -> ext instanceof LoadStepFactory)
			.map(ext -> (LoadStepFactory) ext)
			.collect(Collectors.toList());

		final LoadStepFactory selectedFactory = loadStepFactories
			.stream()
			.filter(f -> stepType.endsWith(f.id()))
			.findFirst()
			.orElseThrow(
				() -> new IllegalStateException(
					"Failed to find the load step implementation for type \"" + stepType +
						"\", available types: " +
						Arrays.toString(
							loadStepFactories.stream().map(LoadStepFactory::id).toArray()
						)
				)
			);

		try(
			final Instance logCtx = CloseableThreadContext
				.put(KEY_CLASS_NAME, BasicLoadStepService.class.getSimpleName())
		) {
			loadStep = selectedFactory.create(config, extensions, stepConfigs);
			Loggers.MSG.info("New step service for \"{}\"", config.stringVal("load-step-id"));
			super.doStart();
		}
	}

	@Override
	protected final void doStart() {
		try(
			final Instance logCtx = CloseableThreadContext
				.put(KEY_CLASS_NAME, BasicLoadStepService.class.getSimpleName())
				.put(KEY_STEP_ID, loadStep.id())
		) {
			loadStep.start();
			Loggers.MSG.info("Step service for \"{}\" is started", loadStep.id());
		} catch(final RemoteException ignored) {
		}
	}

	@Override
	protected void doStop() {
		try(
			final Instance logCtx = CloseableThreadContext
				.put(KEY_CLASS_NAME, BasicLoadStepService.class.getSimpleName())
				.put(KEY_STEP_ID, loadStep.id())
		) {
			loadStep.stop();
			Loggers.MSG.info("Step service for \"{}\" is stopped", loadStep.id());
		} catch(final RemoteException ignored) {
		}
	}

	@Override
	protected final void doClose()
	throws IOException {
		try(
			final Instance logCtx = CloseableThreadContext
				.put(KEY_CLASS_NAME, BasicLoadStepService.class.getSimpleName())
				.put(KEY_STEP_ID, loadStep.id())
		) {
			super.doStop();
			loadStep.close();
			Loggers.MSG.info("Step service for \"{}\" is closed", loadStep.id());
		}
	}

	@Override
	public String name() {
		return SVC_NAME_PREFIX + hashCode();
	}

	@Override
	public LoadStep config(final Map<String, Object> config)
	throws RemoteException {
		return loadStep.config(config);
	}

	@Override
	public final String id()
	throws RemoteException {
		return loadStep.id();
	}

	@Override
	public final String getTypeName()
	throws RemoteException {
		return loadStep.getTypeName();
	}

	@Override
	public final List<MetricsSnapshot> metricsSnapshots()
	throws RemoteException {
		return loadStep.metricsSnapshots();
	}

	@Override
	public boolean await(final long timeout, final TimeUnit timeUnit)
	throws IllegalStateException, InterruptedException {
		try(
			final Instance logCtx = CloseableThreadContext
				.put(KEY_CLASS_NAME, BasicLoadStepService.class.getSimpleName())
				.put(KEY_STEP_ID, loadStep.id())
		) {
			return loadStep.await(timeout, timeUnit);
		} catch(final RemoteException ignored) {
		}
		return false;
	}
}
