ARG MONGOOSE_VERSION

FROM emcmongoose/mongoose-base:${MONGOOSE_VERSION}

ADD ["http://central.maven.org/maven2/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar", "/opt/mongoose/ext/jython-standalone.jar"]
