ARG MONGOOSE_VERSION

FROM emcmongoose/mongoose-base:${MONGOOSE_VERSION}

ADD ["http://central.maven.org/maven2/org/codehaus/groovy/groovy/2.4.12/groovy-2.4.12.jar", "/opt/mongoose/ext/groovy.jar"]
ADD ["http://central.maven.org/maven2/org/codehaus/groovy/groovy-jsr223/2.4.12/groovy-jsr223-2.4.12.jar", "/opt/mongoose/ext/groovy-jsr223.jar"]
