FROM openjdk:8-jre-alpine

MAINTAINER EMC

ADD build/dist/mongoose*.tgz /opt/

RUN ln -s /opt/mongoose* /opt/mongoose

EXPOSE 1099

ENTRYPOINT ["java", "-jar", "/opt/mongoose/mongoose-storage-driver-service.jar"]
