FROM openjdk:8-jre-alpine

ADD build/dist/mongoose-base-*.tgz /opt/

EXPOSE 9010

RUN ln -s /opt/mongoose-* /opt/mongoose

ADD docker/entrypoint.sh /usr/bin/mongoose

RUN chmod +x /usr/bin/mongoose

RUN chmod -R ugo+rwx /opt/mongoose

ENTRYPOINT ["/usr/bin/mongoose", "-jar", "/opt/mongoose/mongoose.jar"]
