FROM openjdk:8-jre-alpine

ADD build/dist/mongoose-storage-driver-service-*.tgz /opt/

EXPOSE 1099

RUN ln -s /opt/mongoose-* /opt/mongoose

ADD docker/entrypoint.sh /usr/bin/mongoose

RUN chmod +x /usr/bin/mongoose

RUN chmod -R ugo+rwx /opt/mongoose

ENTRYPOINT ["/usr/bin/mongoose", "-jar", "/opt/mongoose/mongoose-storage-driver-service.jar"]
