on: [push]
jobs:
  build_job:
    uses:
      emc-mongoose/mongoose-base/.github/workflows/main.yml@master
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_KEY_PASSWORD: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
      GPG_SECRING: ${{ secrets.GPG_SECRING }}
